### PR TITLE
Feat/wasm upload

### PR DESCRIPTION
**Pull request by cnlangzi**

### CODE REVIEW

**Comment by shaktals** [comment]
@cnlangzi I did some minor style adjustments.
Then I updated the explorer code on this [PR](https://github.com/0chain/block-explorer/pull/556).
But I think some functions are not completely functional are they?

- Upload: OK
- Download: get error `binder: mismatched input length`
- Rename: get this [error](https://user-images.githubusercontent.com/24679343/147614809-3d44e91f-fe69-44a8-8e88-be33931b0a51.png)

And I stopped testing there. Can you double check? Thanks.

**Comment by cnlangzi** [comment]
> @cnlangzi I did some minor style adjustments. Then I updated the explorer code on this [PR](https://github.com/0chain/block-explorer/pull/556). But I think some functions are not completely functional are they?
> 
> * Upload: OK
> * Download: get error `binder: mismatched input length`
> * Rename: get this [error](https://user-images.githubusercontent.com/24679343/147614809-3d44e91f-fe69-44a8-8e88-be33931b0a51.png)
> 
> And I stopped testing there. Can you double check? Thanks.

use latest zcn.wasm, and check it again.

**Comment by shaktals** [comment]
@cnlangzi completely forgot about the new binary and the updates to `wasm.js`
I'll try again in the morning.

**Comment by shaktals** [comment]
@cnlangzi cool, on my [explorer PR](https://github.com/0chain/block-explorer/pull/556) I updated the wasm binary and wasm_exec directly from your branch feat/wasm_upload, I also updated some of the code to match your own.

Now all functions are working, except Rename and Share.

For Rename I don't see updates on your explorer PR.

For Share, it creates a link, but when I try to use it on another wallet to receive the shared file, it yields this error:

Selection_298

There seems to be an encoding issue with the auth_ticket. Can you check please? Thanks!

**Comment by cnlangzi** [comment]
> @cnlangzi cool, on my [explorer PR](https://github.com/0chain/block-explorer/pull/556) I updated the wasm binary and wasm_exec directly from your branch feat/wasm_upload, I also updated some of the code to match your own.
> 
> Now all functions are working, except Rename and Share.
> 
> For Rename I don't see updates on your explorer PR.
> 
> For Share, it creates a link, but when I try to use it on another wallet to receive the shared file, it yields this error:
> 
> Selection_298
> 
> There seems to be an encoding issue with the auth_ticket. Can you check please? Thanks!

Got it. let me test it on your PR.

**Comment by cnlangzi** [comment]
@shaktals  I have got both of them are fixed and worked on https://github.com/0chain/block-explorer/pull/556. please try it again, thanks.

**Review by shaktals — APPROVED** [review]

**Pull request merged**
